# Generated by Django 4.2.1 on 2023-08-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=None, verbose_name='')),
                ('userComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.comment', verbose_name='')),
                ('userPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.post', verbose_name='')),
            ],
        ),
    ]
